// 28 tú data (name, element, animal, luận verse) — sourced from lichdungsu.
export interface Tu28 {
  readonly fullName: string;
  readonly name: string;
  readonly element: string;
  readonly animal: string;
  readonly verse: readonly string[];
}

// Indexed in nhithapbattu_sao order: Giốc, Cang, Đê, ...
export const TU_28: readonly Tu28[] = [
  {
    fullName: 'Giốc Mộc Giao',
    name: 'Giốc',
    element: 'Mộc',
    animal: 'Giao Long',
    verse: [
      'Sao Giốc tạo ra người quí sang',
      'Đỗ trạng vua ban đứng nhất hàng',
      'Hôn nhân cưới gả sinh con quí',
      'Động quan sửa mộ chú trùng tang',
    ],
  },
  {
    fullName: 'Cang Kim Long',
    name: 'Cang',
    element: 'Kim',
    animal: 'Rồng',
    verse: [
      'Sao Cang xây cất chịu buồn lòng',
      'Mười ngày tại họa vướng vào trong',
      'An táng hôn nhân như được chọn',
      'Chết non dâu chịu cảnh phòng không',
    ],
  },
  {
    fullName: 'Đê Thổ Lạc',
    name: 'Đê',
    element: 'Thổ',
    animal: 'Lạc Đà',
    verse: [
      'Sao Đê tạo dựng chú hùng phần',
      'Cưới gà hôn nhân họa mấy lần',
      'Đi thuyền bị nước trôi chìm hại',
      'Mai táng dùng xong cháu khổ bần',
    ],
  },
  {
    fullName: 'Phòng Nhật Thỏ',
    name: 'Phòng',
    element: 'Dương Hỏa',
    animal: 'Thỏ',
    verse: [
      'Sao Phòng xây dựng tiền tài đa',
      'Có ngày phú quí với vinh hoa',
      'Mai táng ngày này nếu gặp được',
      'Công hầu phong chức có trong ba',
    ],
  },
  {
    fullName: 'Tâm Nguyệt Hồ',
    name: 'Tâm',
    element: 'Âm Hỏa',
    animal: 'Cáo',
    verse: [
      'Sao Tâm xây dựng lắm hung tai',
      'Các việc khuyên người nên tránh ngay',
      'Chôn cất hôn nhân đều bất lợi',
      'Tai họa ba năm lấp lấp đầy',
    ],
  },
  {
    fullName: 'Vĩ Hỏa Hổ',
    name: 'Vĩ',
    element: 'Hỏa',
    animal: 'Hổ',
    verse: [
      'Sao Vĩ dựng xây tốt khác thường',
      'Giàu sang như tháo nước khai trương',
      'Mai táng hôn nhân như chọn đến',
      'Đời đời khanh tướng chốn quan trường',
    ],
  },
  {
    fullName: 'Cơ Thủy Báo',
    name: 'Cơ',
    element: 'Thủy',
    animal: 'Báo',
    verse: [
      'Sao Cơ xây dựng tốt sao đo',
      'Nhà cử khai trương tài lộc to',
      'Sửa mộ hôn nhân đều cát lợi',
      'Bạc vàng lúa thóc chất tràn kho',
    ],
  },
  {
    fullName: 'Đẩu Mộc Giải',
    name: 'Đẩu',
    element: 'Mộc',
    animal: 'Cua',
    verse: [
      'Sao Đẩu dựng xây tài thuận thông',
      'Táng mai, con cháu đại hưng long',
      'Khai trương tháo nước nhiều tài lợi',
      'Cưới gả hôn nhân vui chất chông',
    ],
  },
  {
    fullName: 'Ngưu Kim Ngưu',
    name: 'Ngưu',
    element: 'Kim',
    animal: 'Trâu',
    verse: [
      'Sao Ngưu xây tạo lắm nguy nan',
      'Bất lợi nông gia chủ thở than',
      'Khai trương cưới gả gây trùng họa',
      'Lục súc dịch ôn phải rã đàn',
    ],
  },
  {
    fullName: 'Nữ Thổ Bức',
    name: 'Nữ',
    element: 'Thổ',
    animal: 'Dơi',
    verse: [
      'Sao Nữ tạo xây vợ khó an',
      'Anh em như sói cọp tương tàn',
      'Hôn nhân chôn cất như dùng tới',
      'Lìa quê tay trắng sống lang thang',
    ],
  },
  {
    fullName: 'Hư Nhật Thử',
    name: 'Hư',
    element: 'Dương Hỏa',
    animal: 'Chuột',
    verse: [
      'Sao Hư tạo dựng xấu mười mươi',
      'Nam nữ riêng phòng cách mỗi nơi',
      'Rối rắm tiếng đời vô lễ giáo',
      'Cháu con dâu phải ngủ giường người',
    ],
  },
  {
    fullName: 'Nguy Nguyệt Yến',
    name: 'Nguy',
    element: 'Âm Hỏa',
    animal: 'Chim Yến',
    verse: [
      'Sao Nguy không xây tạo nhà cao',
      'Sửa mộ động quan thấy màu đào',
      'Tháo nước khai trương hình phật gậy',
      'Ba năm con cháu nạn như nhau',
    ],
  },
  {
    fullName: 'Thất Hỏa Trư',
    name: 'Thất',
    element: 'Hỏa',
    animal: 'Lợn',
    verse: [
      'Sao Thất dựng xây lắm ngựa trâu',
      'Cháu con nối tiếp chức công hầu',
      'Lập nghiệp thêm tài nhà cửa đẹp',
      'Hôn nhân mai táng chẳng âu sầu',
    ],
  },
  {
    fullName: 'Bích Thủy Du',
    name: 'Bích',
    element: 'Thủy',
    animal: 'Nhím',
    verse: [
      'Sao bích dựng xây lộc rạng ngời',
      'Hôn nhân gẩ cưới mãi vui tươi',
      'Động quan lập nghiệp giàu con cháu',
      'Tháo nước khai trương được gặp thời',
    ],
  },
  {
    fullName: 'Khuê Mộc Lang',
    name: 'Khuê',
    element: 'Mộc',
    animal: 'Sói',
    verse: [
      'Sao Khuê xây dựng thêm điểm lành',
      'Hòa thuận gia đình tốt rạng danh',
      'Dùng ngày chôn cất thêm người mất',
      'Khai trương tai họa vướng vào nhanh',
    ],
  },
  {
    fullName: 'Lâu Kim Cẩu',
    name: 'Lâu',
    element: 'Kim',
    animal: 'Chó',
    verse: [
      'Sao Lâu như ngọc cửa thiên đình',
      'Xây nhà giàu có việc việc vinh',
      'Hôn nhân sau được sinh con quí',
      'Quan lộc đời đời nhậm đế kinh',
    ],
  },
  {
    fullName: 'Vị Thổ Trĩ',
    name: 'Vị',
    element: 'Thổ',
    animal: 'Chim Trĩ',
    verse: [
      'Sao Vị dựng xây việc thế nào',
      'Phú quí vinh hoa vui xiết bao',
      'Mai táng thăng quan thêm tước vị',
      'Hôn nhân hòa thuận nều dùng vào',
    ],
  },
  {
    fullName: 'Mão Nhật Kê',
    name: 'Mão',
    element: 'Dương Hỏa',
    animal: 'Gà',
    verse: [
      'Sao Mão dựng xây nhiều ruộng trâu',
      'Mai táng quan hình phải vướng lâu',
      'Khai trương bị tới nhiều tai họa',
      'Hôn nhân cưới gả lắm âu sầu',
    ],
  },
  {
    fullName: 'Tất Nguyệt Ô',
    name: 'Tất',
    element: 'Âm Hỏa',
    animal: 'Qụa',
    verse: [
      'Sao Tất tạo xây mãi sáng ngời',
      'Vườn ruộng trúng mùa được thảnh thơi',
      'Cả nhà luôn gặp niềm vui đến',
      'Hôn nhân mai táng thọ đời đời',
    ],
  },
  {
    fullName: 'Chủy Hỏa Cầu',
    name: 'Chủy',
    element: 'Hỏa',
    animal: 'Khỉ',
    verse: [
      'Sao Chủy dựng xây rối bận lòng',
      'Mai táng không lâu nhà bại vọng',
      'Trùng tang điểm gở điều do đấy',
      'Vàng bạc kho hàng cũng trống không',
    ],
  },
  {
    fullName: 'Sâm Thủy Viên',
    name: 'Sâm',
    element: 'Thủy',
    animal: 'Vượn',
    verse: [
      'Sao Sâm tạo dựng hãy khoe ra',
      'Thịnh vượng văn tinh chiếu sáng lòa',
      'Khai trương canh tác nhiều điểm tốt',
      'Chôn cất hôn nhân chủ phá gia',
    ],
  },
  {
    fullName: 'Tỉnh Mộc Ngạn',
    name: 'Tỉnh',
    element: 'Mộc',
    animal: 'Chim Ngạn',
    verse: [
      'Sao Tỉnh tạo xây tốt bá niên',
      'Tên viết bảng vàng đỗ trạng nguyên',
      'Động quan phòng kỷ(đề phòng) người thêm mất',
      'Khai trương liền được lãi nhiều tiền',
    ],
  },
  {
    fullName: 'Quỷ Kim Dương',
    name: 'Quỷ',
    element: 'Kim',
    animal: 'Dê',
    verse: [
      'Sao quỷ dựng xây người tử vong',
      'Trong nhà đâu thấy bóng người chồng',
      'Động qua như thể chôn quan lộc',
      'Hôn nhân phải chịu cảnh phòng không',
    ],
  },
  {
    fullName: 'Liễu Thổ Chương',
    name: 'Liễu',
    element: 'Thổ',
    animal: 'Con Cheo',
    verse: [
      'Sao Liễu dựng xây vướng cửa quan',
      'Trộm cướp họa tai nhà chẳng an',
      'Hôn nhân chôn cất như dùng tới',
      'Ba năm con cháu phải sầu mang',
    ],
  },
  {
    fullName: 'Tinh Nhật Mã',
    name: 'Tinh',
    element: 'Dương Hỏa',
    animal: 'Ngựa',
    verse: [
      'Sao Tinh tỏ rạng hợp xây nhà',
      'Vua ban quan lộc mãi thăng hoa',
      'Khai trương không hợp cùng mai táng',
      'Vợ gả cho người cách biệt xa',
    ],
  },
  {
    fullName: 'Trương Nguyệt Lộc',
    name: 'Trương',
    element: 'Âm Hỏa',
    animal: 'Hươu',
    verse: [
      'Sao Trương ngày tốt cất lâu đài',
      'Đời đời quan tước cạnh long ngai',
      'Chôn cất khai trương càn phú quí',
      'Hôn nhân hòa hợp phúc lâu dài',
    ],
  },
  {
    fullName: 'Dực Hòa Xà',
    name: 'Dực',
    element: 'Hỏa',
    animal: 'Rắn',
    verse: [
      'Sao Dực kỵ xây cất nhà lầu',
      'Ba năm gia chủ mãi lo âu',
      'Mai táng hôn nhân đều bất lợi',
      'Thiếu nữ phong lưu hướng ngoại cầu',
    ],
  },
  {
    fullName: 'Chẩn Thủy Dẫn',
    name: 'Chẩn',
    element: 'Thủy',
    animal: 'Con Giun',
    verse: [
      'Sao chẩn tạo xây thăng tước quan',
      'Hôn ước vua ban được rở ràng',
      'Mai táng sao văn thêm chiếu rọi',
      'Ngày một giàu sang tích ngọc vàng',
    ],
  },
];

// Day-tú cycle order (TINH28): starts at Hư.
export const TINH28_ORDER = [
  'Hư',
  'Nguy',
  'Thất',
  'Bích',
  'Khuê',
  'Lâu',
  'Vị',
  'Mão',
  'Tất',
  'Chủy',
  'Sâm',
  'Tỉnh',
  'Quỷ',
  'Liễu',
  'Tinh',
  'Trương',
  'Dực',
  'Chẩn',
  'Giác',
  'Cang',
  'Đê',
  'Phòng',
  'Tâm',
  'Vĩ',
  'Cơ',
  'Đẩu',
  'Ngưu',
  'Nữ',
] as const;
