app:
  name: APP_NAME
  port:
    __name: PORT
    __format: number
  nodeEnv: NODE_ENV
  url: APP_URL
  trustProxy:
    __name: TRUST_PROXY
    __format: number
  logLevels: LOG_LEVELS

db:
  primary:
    host: DB_HOST
    port:
      __name: DB_PORT
      __format: number
  username: DB_USERNAME
  password: DB_PASSWORD
  database: DB_NAME
  tls:
    __name: DB_TLS
    __format: boolean
  log:
    enabled:
      __name: DB_LOG_ENABLED
      __format: boolean

redis:
  host: REDIS_HOST
  port:
    __name: REDIS_PORT
    __format: number
  password: REDIS_PASSWORD
  db:
    __name: REDIS_DB
    __format: number
  tls:
    __name: REDIS_TLS
    __format: boolean

sentry:
  dsn: SENTRY_DSN
  tracesSampleRate:
    __name: SENTRY_TRACES_SAMPLE_RATE
    __format: number

cors:
  origins: CORS_ORIGINS

jwt:
  secret: JWT_SECRET
  accessTokenExpiresIn: JWT_ACCESS_TOKEN_EXPIRES_IN

crypto:
  secretKey: SECRET_KEY

email:
  resendApiKey: RESEND_API_KEY
  from: EMAIL_FROM

session:
  maxSessionsPerUser:
    __name: MAX_SESSIONS_PER_USER
    __format: number
  refreshTtl: SESSION_REFRESH_TTL
  refreshTtlRemember: SESSION_REFRESH_TTL_REMEMBER
  refreshTtlOauth: SESSION_REFRESH_TTL_OAUTH

captcha:
  enabled:
    __name: CAPTCHA_ENABLED
    __format: boolean
  secretKey: CAPTCHA_SECRET_KEY

google:
  clientId: GOOGLE_CLIENT_ID

queueBoard:
  user: QUEUE_BOARD_USER
  password: QUEUE_BOARD_PASSWORD
