app:
  name: My Workspace
  port: 3000
  nodeEnv: development
  url: http://localhost:4200
  trustProxy: 0
  logLevels:
    - error
    - warn
    - log
    - debug
    - verbose

db:
  username: postgres
  password: password
  database: nestdb
  tls: false
  primary:
    host: localhost
    port: 5432
  replicas: []
  log:
    enabled: true

redis:
  cluster: false
  password: ''
  tls: false
  host: localhost
  port: 6379
  db: 0

sentry:
  dsn: ''
  tracesSampleRate: 0.1

cors:
  origins:
    - http://localhost:4200

jwt:
  secret: super-secret-key
  accessTokenExpiresIn: 15m

crypto:
  secretKey: yoursecretkeymustbe32characters!!

email:
  resendApiKey: ''
  from: Acme <onboarding@resend.dev>

session:
  maxSessionsPerUser: 5
  refreshTtl: 1d
  refreshTtlRemember: 60d
  refreshTtlOauth: 30d

captcha:
  enabled: false
  secretKey: ''

google:
  clientId: ''
