app:
  nodeEnv: production
  url: https://xemtuvimienphi.top
  trustProxy: 1
  logLevels:
    - error
    - warn
    - log

db:
  tls: true
  log:
    enabled: false

redis:
  tls: true

cors:
  origins:
    - https://xemtuvimienphi.top
    - https://www.xemtuvimienphi.top
    - https://tuvimienphi-frontend.vercel.app

queueBoard:
  enabled: false
