import type { NguHanh } from '@/lib/nap-am';
import type { ChinhTinhName, PhuTinhName } from '@/lib/tu-vi/sao-names';

/**
 * Ngũ hành của từng sao. Chép từ tuvi.vn, nơi mỗi sao mang sẵn một mã màu nội tuyến — năm mã ấy
 * chính là năm hành, đối chiếu lại với sách thì khớp (Tử Vi Thổ, Thiên Cơ Mộc, Thái Dương Hỏa,
 * Vũ Khúc Kim, Thiên Đồng Thủy…).
 *
 * Hành quyết định màu chữ của sao trên lá số, không tham gia vào việc an sao.
 */

/** Mười bốn chính tinh. */
export const CHINH_TINH_NGU_HANH: Readonly<Record<ChinhTinhName, NguHanh>> = {
  'Tử Vi': 'Thổ',
  'Thiên Cơ': 'Mộc',
  'Thái Dương': 'Hỏa',
  'Vũ Khúc': 'Kim',
  'Thiên Đồng': 'Thủy',
  'Liêm Trinh': 'Hỏa',
  'Thiên Phủ': 'Thổ',
  'Thái Âm': 'Thủy',
  'Tham Lang': 'Thủy',
  'Cự Môn': 'Thủy',
  'Thiên Tướng': 'Thủy',
  'Thiên Lương': 'Mộc',
  'Thất Sát': 'Kim',
  'Phá Quân': 'Thủy',
};

/** Tám mươi ba phụ tinh engine an được. */
export const PHU_TINH_NGU_HANH: Readonly<Record<PhuTinhName, NguHanh>> = {
  'Linh Tinh': 'Hỏa',
  'Hỏa Tinh': 'Hỏa',
  'Bác Sỹ': 'Thủy',
  'Bát Tọa': 'Mộc',
  'Bạch Hổ': 'Kim',
  'Bệnh Phù': 'Thổ',
  'Cô Thần': 'Thổ',
  'Giải Thần': 'Mộc',
  'Hoa Cái': 'Kim',
  'Hóa Khoa': 'Thủy',
  'Hóa Kỵ': 'Thủy',
  'Hóa Lộc': 'Mộc',
  'Hóa Quyền': 'Thủy',
  'Hồng Loan': 'Thủy',
  'Hữu Bật': 'Thủy',
  'Hỷ Thần': 'Hỏa',
  'Kiếp Sát': 'Hỏa',
  'Kình Dương': 'Kim',
  'Long Trì': 'Thủy',
  'Long Đức': 'Thủy',
  'Lưu Hà': 'Thủy',
  'Lộc Tồn': 'Thổ',
  'Lực Sỹ': 'Thủy',
  'Nguyệt Đức': 'Hỏa',
  'Phi Liêm': 'Hỏa',
  'Phong Cáo': 'Thổ',
  'Phá Toái': 'Hỏa',
  'Phúc Đức': 'Thổ',
  'Phượng Các': 'Thổ',
  'Phục Binh': 'Hỏa',
  'Quan Phù': 'Hỏa',
  'Quan Phủ': 'Hỏa',
  'Quả Tú': 'Thổ',
  'Quốc Ấn': 'Thổ',
  'Tam Thai': 'Thủy',
  'Tang Môn': 'Mộc',
  'Thai Phụ': 'Kim',
  'Thanh Long': 'Thủy',
  'Thiên Diêu': 'Thủy',
  'Thiên Giải': 'Hỏa',
  'Thiên Hình': 'Hỏa',
  'Thiên Hư': 'Thủy',
  'Thiên Hỉ': 'Thủy',
  'Thiên Khôi': 'Hỏa',
  'Thiên Không': 'Hỏa',
  'Thiên Khốc': 'Thủy',
  'Thiên La': 'Kim',
  'Thiên Mã': 'Hỏa',
  'Thiên Phúc': 'Thổ',
  'Thiên Quan': 'Hỏa',
  'Thiên Quý': 'Thổ',
  'Thiên Sứ': 'Thủy',
  'Thiên Thương': 'Thổ',
  'Thiên Thọ': 'Thổ',
  'Thiên Trù': 'Thổ',
  'Thiên Tài': 'Thổ',
  'Thiên Việt': 'Hỏa',
  'Thiên Y': 'Thủy',
  'Thiên Đức': 'Thổ',
  'Thiếu Dương': 'Hỏa',
  'Thiếu Âm': 'Thủy',
  'Thái Tuế': 'Hỏa',
  'Tiểu Hao': 'Hỏa',
  'Trực Phù': 'Kim',
  'Tuế Phá': 'Hỏa',
  'Tướng Quân': 'Mộc',
  'Tả Phù': 'Thổ',
  'Tấu Thư': 'Kim',
  'Tử Phù': 'Kim',
  'Văn Khúc': 'Thủy',
  'Văn Tinh': 'Hỏa',
  'Văn Xương': 'Kim',
  'Ân Quang': 'Mộc',
  'Điếu Khách': 'Hỏa',
  'Đà La': 'Kim',
  'Đào Hoa': 'Mộc',
  'Đường Phù': 'Mộc',
  'Đại Hao': 'Hỏa',
  'Đầu Quân': 'Hỏa',
  'Địa Giải': 'Thổ',
  'Địa Không': 'Hỏa',
  'Địa Kiếp': 'Hỏa',
  'Địa Võng': 'Kim',
};

/**
 * Âm dương của mười bốn chính tinh, in thành dấu trước tên sao trên lá số. Là thuộc tính cố định
 * của sao, không phụ thuộc cung nó đóng.
 */
export const CHINH_TINH_POLARITY: Readonly<Record<ChinhTinhName, string>> = {
  'Tử Vi': '+',
  'Thiên Cơ': '-',
  'Thái Dương': '+',
  'Vũ Khúc': '-',
  'Thiên Đồng': '+',
  'Liêm Trinh': '-',
  'Thiên Phủ': '-',
  'Thái Âm': '-',
  'Tham Lang': '-',
  'Cự Môn': '-',
  'Thiên Tướng': '+',
  'Thiên Lương': '+',
  'Thất Sát': '+',
  'Phá Quân': '-',
};
