/**
 * Tên của mọi sao engine an được — nguồn duy nhất để các bảng tra và các hàm an sao cùng tham chiếu.
 * Nhờ `SaoName`, một tên gõ sai thành lỗi biên dịch thay vì một sao lặng lẽ biến mất khỏi lá số.
 */

export const CHINH_TINH_NAMES = [
  'Tử Vi',
  'Thiên Cơ',
  'Thái Dương',
  'Vũ Khúc',
  'Thiên Đồng',
  'Liêm Trinh',
  'Thiên Phủ',
  'Thái Âm',
  'Tham Lang',
  'Cự Môn',
  'Thiên Tướng',
  'Thiên Lương',
  'Thất Sát',
  'Phá Quân',
] as const;

export type ChinhTinhName = (typeof CHINH_TINH_NAMES)[number];

/** Gồm cả bốn hoá khí, vì chúng đóng tại cung của sao nhận hoá và in ra như một phụ tinh. */
export const PHU_TINH_NAMES = [
  'Linh Tinh',
  'Hỏa Tinh',
  'Bác Sỹ',
  'Bát Tọa',
  'Bạch Hổ',
  'Bệnh Phù',
  'Cô Thần',
  'Giải Thần',
  'Hoa Cái',
  'Hóa Khoa',
  'Hóa Kỵ',
  'Hóa Lộc',
  'Hóa Quyền',
  'Hồng Loan',
  'Hữu Bật',
  'Hỷ Thần',
  'Kiếp Sát',
  'Kình Dương',
  'Long Trì',
  'Long Đức',
  'Lưu Hà',
  'Lộc Tồn',
  'Lực Sỹ',
  'Nguyệt Đức',
  'Phi Liêm',
  'Phong Cáo',
  'Phá Toái',
  'Phúc Đức',
  'Phượng Các',
  'Phục Binh',
  'Quan Phù',
  'Quan Phủ',
  'Quả Tú',
  'Quốc Ấn',
  'Tam Thai',
  'Tang Môn',
  'Thai Phụ',
  'Thanh Long',
  'Thiên Diêu',
  'Thiên Giải',
  'Thiên Hình',
  'Thiên Hư',
  'Thiên Hỉ',
  'Thiên Khôi',
  'Thiên Không',
  'Thiên Khốc',
  'Thiên La',
  'Thiên Mã',
  'Thiên Phúc',
  'Thiên Quan',
  'Thiên Quý',
  'Thiên Sứ',
  'Thiên Thương',
  'Thiên Thọ',
  'Thiên Trù',
  'Thiên Tài',
  'Thiên Việt',
  'Thiên Y',
  'Thiên Đức',
  'Thiếu Dương',
  'Thiếu Âm',
  'Thái Tuế',
  'Tiểu Hao',
  'Trực Phù',
  'Tuế Phá',
  'Tướng Quân',
  'Tả Phù',
  'Tấu Thư',
  'Tử Phù',
  'Văn Khúc',
  'Văn Tinh',
  'Văn Xương',
  'Ân Quang',
  'Điếu Khách',
  'Đà La',
  'Đào Hoa',
  'Đường Phù',
  'Đại Hao',
  'Đầu Quân',
  'Địa Giải',
  'Địa Không',
  'Địa Kiếp',
  'Địa Võng',
] as const;

export type PhuTinhName = (typeof PHU_TINH_NAMES)[number];

export type SaoName = ChinhTinhName | PhuTinhName;
