/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdsRouteImport } from './routes/ads'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as UsersRouteImport } from './routes/users'
import { Route as VanHanRouteImport } from './routes/van-han'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsRoute = AdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const VanHanRoute = VanHanRouteImport.update({
  id: '/van-han',
  path: '/van-han',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/blog': typeof BlogRoute
  '/profile': typeof ProfileRoute
  '/users': typeof UsersRoute
  '/van-han': typeof VanHanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/blog': typeof BlogRoute
  '/profile': typeof ProfileRoute
  '/users': typeof UsersRoute
  '/van-han': typeof VanHanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/blog': typeof BlogRoute
  '/profile': typeof ProfileRoute
  '/users': typeof UsersRoute
  '/van-han': typeof VanHanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ads' | '/blog' | '/profile' | '/users' | '/van-han'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ads' | '/blog' | '/profile' | '/users' | '/van-han'
  id: '__root__' | '/' | '/ads' | '/blog' | '/profile' | '/users' | '/van-han'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdsRoute: typeof AdsRoute
  BlogRoute: typeof BlogRoute
  ProfileRoute: typeof ProfileRoute
  UsersRoute: typeof UsersRoute
  VanHanRoute: typeof VanHanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads': {
      id: '/ads'
      path: '/ads'
      fullPath: '/ads'
      preLoaderRoute: typeof AdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/van-han': {
      id: '/van-han'
      path: '/van-han'
      fullPath: '/van-han'
      preLoaderRoute: typeof VanHanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdsRoute: AdsRoute,
  BlogRoute: BlogRoute,
  ProfileRoute: ProfileRoute,
  UsersRoute: UsersRoute,
  VanHanRoute: VanHanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
