import type { PhuTinhName } from '../../../sao-names.js';
import { Sac, type LuanDe } from '../../luan-de.js';

export const PHU_TINH_QUAN_LOC: Readonly<Partial<Record<PhuTinhName, LuanDe>>> = {
  'Đại Hao': {
    y: 'hao tổn nhiều công sức và tiền bạc cho công việc mà chưa thấy thu lại tương xứng',
    do: ['Đại Hao'],
    sac: Sac.Nghich,
    trong: 65,
    tuKhoa: ['hao tổn', 'công sức', 'chưa thấy thu lại'],
  },
  'Kiếp Sát': {
    y: 'có giai đoạn công việc gặp biến cố bất ngờ, mất đi phần thành quả đã gây dựng',
    do: ['Kiếp Sát'],
    sac: Sac.Nghich,
    trong: 60,
    tuKhoa: ['biến cố bất ngờ', 'mất đi thành quả'],
  },
  'Thiên Diêu': {
    y: 'dễ sa đà vào việc ngoài lề, phân tán sức tập trung khỏi việc chính',
    do: ['Thiên Diêu'],
    sac: Sac.Nghich,
    trong: 60,
    tuKhoa: ['sa đà việc ngoài lề', 'phân tán'],
  },
  'Đà La': {
    y: 'trắc trở kéo dài, việc gì cũng chậm và dây dưa',
    do: ['Đà La'],
    sac: Sac.Nghich,
    trong: 62,
    tuKhoa: ['trắc trở', 'chậm', 'dây dưa'],
  },
  'Cô Thần': {
    y: 'nhiều lúc phải tự xoay sở một mình, ít người cùng gánh việc',
    do: ['Cô Thần'],
    sac: Sac.Nghich,
    trong: 58,
    tuKhoa: ['tự xoay sở một mình', 'ít người cùng gánh'],
  },
  'Phá Toái': {
    y: 'công việc dễ gián đoạn hoặc đứt quãng giữa chừng',
    do: ['Phá Toái'],
    sac: Sac.Nghich,
    trong: 55,
    tuKhoa: ['gián đoạn', 'đứt quãng'],
  },
  'Thiên Không': {
    y: 'dễ hụt hẫng vì kỳ vọng vào công việc không khớp thực tế',
    do: ['Thiên Không'],
    sac: Sac.Nghich,
    trong: 55,
    tuKhoa: ['hụt hẫng', 'kỳ vọng'],
  },
  'Kình Dương': {
    y: 'dễ va chạm, lời qua tiếng lại với người cùng làm',
    do: ['Kình Dương'],
    sac: Sac.Nghich,
    trong: 55,
    tuKhoa: ['va chạm', 'lời qua tiếng lại'],
  },
  'Hỏa Tinh': {
    y: 'tính khí nóng, xung đột trong công việc đến nhanh đi nhanh',
    do: ['Hỏa Tinh'],
    sac: Sac.Nghich,
    trong: 50,
    tuKhoa: ['nóng', 'xung đột'],
  },
  'Linh Tinh': {
    y: 'uất ức âm ỉ vì công việc, khó nói thẳng ra',
    do: ['Linh Tinh'],
    sac: Sac.Nghich,
    trong: 50,
    tuKhoa: ['uất ức', 'khó nói'],
  },
  'Thiên Hình': {
    y: 'nguyên tắc cứng trong công việc, dễ thành khắc khẩu với đồng nghiệp',
    do: ['Thiên Hình'],
    sac: Sac.Nghich,
    trong: 50,
    tuKhoa: ['nguyên tắc', 'khắc khẩu'],
  },
  'Địa Không': {
    y: 'có giai đoạn công sức bỏ ra không đọng lại thành quả như mong đợi',
    do: ['Địa Không'],
    sac: Sac.Nghich,
    trong: 62,
    tuKhoa: ['không đọng lại', 'như mong đợi'],
  },
  'Tiểu Hao': {
    y: 'hao phí vặt vì những việc lặt vặt phát sinh ngoài kế hoạch',
    do: ['Tiểu Hao'],
    sac: Sac.Nghich,
    trong: 45,
    tuKhoa: ['hao phí vặt', 'ngoài kế hoạch'],
  },
  'Hóa Quyền': {
    y: 'có thực quyền, tiếng nói đủ sức quyết định trong công việc',
    do: ['Hóa Quyền'],
    sac: Sac.Thuan,
    trong: 68,
    tuKhoa: ['thực quyền', 'quyết định'],
  },
  'Hóa Lộc': {
    y: 'công việc đi kèm tài lộc, thu nhập thuận theo công sức bỏ ra',
    do: ['Hóa Lộc'],
    sac: Sac.Thuan,
    trong: 58,
    tuKhoa: ['tài lộc', 'thu nhập'],
  },
  'Thiên Khôi': {
    y: 'gặp việc khó thường có quý nhân đỡ một tay',
    do: ['Thiên Khôi'],
    sac: Sac.HoaGiai,
    trong: 52,
    tuKhoa: ['quý nhân'],
  },
  'Hồng Loan': {
    y: 'dễ được chú ý đúng lúc, có duyên gặp cơ hội hoặc đối tác tốt',
    do: ['Hồng Loan'],
    sac: Sac.Thuan,
    trong: 62,
    tuKhoa: ['được chú ý đúng lúc', 'duyên gặp cơ hội'],
  },
  'Thiên Y': {
    y: 'dễ gây thiện cảm, được tín nhiệm khi làm việc cùng người khác',
    do: ['Thiên Y'],
    sac: Sac.Thuan,
    trong: 45,
    tuKhoa: ['gây thiện cảm', 'được tín nhiệm'],
  },
  'Đào Hoa': {
    y: 'có sức hút tự nhiên, dễ được chú ý trong tập thể',
    do: ['Đào Hoa'],
    sac: Sac.Thuan,
    trong: 45,
    tuKhoa: ['sức hút tự nhiên', 'được chú ý'],
  },
  'Bát Tọa': {
    y: 'có chỗ đứng, được nể trọng trong tập thể',
    do: ['Bát Tọa'],
    sac: Sac.Thuan,
    trong: 40,
    tuKhoa: ['có chỗ đứng', 'được nể trọng'],
  },
  'Thiên Thọ': {
    y: 'có yếu tố bền, giữ được lâu khi công việc đã ổn định',
    do: ['Thiên Thọ'],
    sac: Sac.HoaGiai,
    trong: 55,
    tuKhoa: ['bền', 'giữ được lâu'],
  },
  'Nguyệt Đức': {
    y: 'có phúc đức che chở, gặp việc khó thường có người đỡ',
    do: ['Nguyệt Đức'],
    sac: Sac.HoaGiai,
    trong: 50,
    tuKhoa: ['che chở', 'người đỡ'],
  },
  'Thiên Đức': {
    y: 'có đức che chở, việc khó hoá nhẹ',
    do: ['Thiên Đức'],
    sac: Sac.HoaGiai,
    trong: 50,
    tuKhoa: ['che chở', 'hoá nhẹ'],
  },
  'Thiên Hỉ': {
    y: 'có tin vui về công việc, không khí làm việc hoà hợp hơn',
    do: ['Thiên Hỉ'],
    sac: Sac.HoaGiai,
    trong: 45,
    tuKhoa: ['tin vui', 'hòa hợp'],
  },
};
