/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as SiteKienThucRouteImport } from './routes/_site/kien-thuc'
import { Route as SiteLaSoRouteImport } from './routes/_site/la-so'
import { Route as SiteNgayTotRouteImport } from './routes/_site/ngay-tot'
import { Route as SiteVanHanRouteImport } from './routes/_site/van-han'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as SiteKienThucIndexRouteImport } from './routes/_site/kien-thuc.index'
import { Route as SiteKienThucSlugRouteImport } from './routes/_site/kien-thuc.$slug'
import { Route as SiteLaSoIndexRouteImport } from './routes/_site/la-so.index'
import { Route as SiteLaSoDetailRouteImport } from './routes/_site/la-so.detail'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteKienThucRoute = SiteKienThucRouteImport.update({
  id: '/kien-thuc',
  path: '/kien-thuc',
  getParentRoute: () => SiteRoute,
} as any)
const SiteLaSoRoute = SiteLaSoRouteImport.update({
  id: '/la-so',
  path: '/la-so',
  getParentRoute: () => SiteRoute,
} as any)
const SiteNgayTotRoute = SiteNgayTotRouteImport.update({
  id: '/ngay-tot',
  path: '/ngay-tot',
  getParentRoute: () => SiteRoute,
} as any)
const SiteVanHanRoute = SiteVanHanRouteImport.update({
  id: '/van-han',
  path: '/van-han',
  getParentRoute: () => SiteRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteKienThucIndexRoute = SiteKienThucIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteKienThucRoute,
} as any)
const SiteKienThucSlugRoute = SiteKienThucSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SiteKienThucRoute,
} as any)
const SiteLaSoIndexRoute = SiteLaSoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteLaSoRoute,
} as any)
const SiteLaSoDetailRoute = SiteLaSoDetailRouteImport.update({
  id: '/detail',
  path: '/detail',
  getParentRoute: () => SiteLaSoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/kien-thuc': typeof SiteKienThucRouteWithChildren
  '/la-so': typeof SiteLaSoRouteWithChildren
  '/ngay-tot': typeof SiteNgayTotRoute
  '/van-han': typeof SiteVanHanRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/kien-thuc/$slug': typeof SiteKienThucSlugRoute
  '/la-so/detail': typeof SiteLaSoDetailRoute
  '/kien-thuc/': typeof SiteKienThucIndexRoute
  '/la-so/': typeof SiteLaSoIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/ngay-tot': typeof SiteNgayTotRoute
  '/van-han': typeof SiteVanHanRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/': typeof SiteIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/kien-thuc/$slug': typeof SiteKienThucSlugRoute
  '/la-so/detail': typeof SiteLaSoDetailRoute
  '/kien-thuc': typeof SiteKienThucIndexRoute
  '/la-so': typeof SiteLaSoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/_site/kien-thuc': typeof SiteKienThucRouteWithChildren
  '/_site/la-so': typeof SiteLaSoRouteWithChildren
  '/_site/ngay-tot': typeof SiteNgayTotRoute
  '/_site/van-han': typeof SiteVanHanRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/_site/': typeof SiteIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/_site/kien-thuc/$slug': typeof SiteKienThucSlugRoute
  '/_site/la-so/detail': typeof SiteLaSoDetailRoute
  '/_site/kien-thuc/': typeof SiteKienThucIndexRoute
  '/_site/la-so/': typeof SiteLaSoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/kien-thuc'
    | '/la-so'
    | '/ngay-tot'
    | '/van-han'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/kien-thuc/$slug'
    | '/la-so/detail'
    | '/kien-thuc/'
    | '/la-so/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/ngay-tot'
    | '/van-han'
    | '/dashboard/settings'
    | '/'
    | '/dashboard'
    | '/kien-thuc/$slug'
    | '/la-so/detail'
    | '/kien-thuc'
    | '/la-so'
  id:
    | '__root__'
    | '/_site'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/_site/kien-thuc'
    | '/_site/la-so'
    | '/_site/ngay-tot'
    | '/_site/van-han'
    | '/dashboard/settings'
    | '/_site/'
    | '/dashboard/'
    | '/_site/kien-thuc/$slug'
    | '/_site/la-so/detail'
    | '/_site/kien-thuc/'
    | '/_site/la-so/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/kien-thuc': {
      id: '/_site/kien-thuc'
      path: '/kien-thuc'
      fullPath: '/kien-thuc'
      preLoaderRoute: typeof SiteKienThucRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/la-so': {
      id: '/_site/la-so'
      path: '/la-so'
      fullPath: '/la-so'
      preLoaderRoute: typeof SiteLaSoRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/ngay-tot': {
      id: '/_site/ngay-tot'
      path: '/ngay-tot'
      fullPath: '/ngay-tot'
      preLoaderRoute: typeof SiteNgayTotRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/van-han': {
      id: '/_site/van-han'
      path: '/van-han'
      fullPath: '/van-han'
      preLoaderRoute: typeof SiteVanHanRouteImport
      parentRoute: typeof SiteRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/kien-thuc/': {
      id: '/_site/kien-thuc/'
      path: '/'
      fullPath: '/kien-thuc/'
      preLoaderRoute: typeof SiteKienThucIndexRouteImport
      parentRoute: typeof SiteKienThucRoute
    }
    '/_site/kien-thuc/$slug': {
      id: '/_site/kien-thuc/$slug'
      path: '/$slug'
      fullPath: '/kien-thuc/$slug'
      preLoaderRoute: typeof SiteKienThucSlugRouteImport
      parentRoute: typeof SiteKienThucRoute
    }
    '/_site/la-so/': {
      id: '/_site/la-so/'
      path: '/'
      fullPath: '/la-so/'
      preLoaderRoute: typeof SiteLaSoIndexRouteImport
      parentRoute: typeof SiteLaSoRoute
    }
    '/_site/la-so/detail': {
      id: '/_site/la-so/detail'
      path: '/detail'
      fullPath: '/la-so/detail'
      preLoaderRoute: typeof SiteLaSoDetailRouteImport
      parentRoute: typeof SiteLaSoRoute
    }
  }
}

interface SiteKienThucRouteChildren {
  SiteKienThucSlugRoute: typeof SiteKienThucSlugRoute
  SiteKienThucIndexRoute: typeof SiteKienThucIndexRoute
}

const SiteKienThucRouteChildren: SiteKienThucRouteChildren = {
  SiteKienThucSlugRoute: SiteKienThucSlugRoute,
  SiteKienThucIndexRoute: SiteKienThucIndexRoute,
}

const SiteKienThucRouteWithChildren = SiteKienThucRoute._addFileChildren(
  SiteKienThucRouteChildren,
)

interface SiteLaSoRouteChildren {
  SiteLaSoDetailRoute: typeof SiteLaSoDetailRoute
  SiteLaSoIndexRoute: typeof SiteLaSoIndexRoute
}

const SiteLaSoRouteChildren: SiteLaSoRouteChildren = {
  SiteLaSoDetailRoute: SiteLaSoDetailRoute,
  SiteLaSoIndexRoute: SiteLaSoIndexRoute,
}

const SiteLaSoRouteWithChildren = SiteLaSoRoute._addFileChildren(
  SiteLaSoRouteChildren,
)

interface SiteRouteChildren {
  SiteKienThucRoute: typeof SiteKienThucRouteWithChildren
  SiteLaSoRoute: typeof SiteLaSoRouteWithChildren
  SiteNgayTotRoute: typeof SiteNgayTotRoute
  SiteVanHanRoute: typeof SiteVanHanRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteKienThucRoute: SiteKienThucRouteWithChildren,
  SiteLaSoRoute: SiteLaSoRouteWithChildren,
  SiteNgayTotRoute: SiteNgayTotRoute,
  SiteVanHanRoute: SiteVanHanRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
