/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as SiteGieoQueRouteImport } from './routes/_site/gieo-que'
import { Route as SiteLaSoRouteImport } from './routes/_site/la-so'
import { Route as SiteLichAmRouteImport } from './routes/_site/lich-am'
import { Route as SiteNgayTotRouteImport } from './routes/_site/ngay-tot'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteGieoQueRoute = SiteGieoQueRouteImport.update({
  id: '/gieo-que',
  path: '/gieo-que',
  getParentRoute: () => SiteRoute,
} as any)
const SiteLaSoRoute = SiteLaSoRouteImport.update({
  id: '/la-so',
  path: '/la-so',
  getParentRoute: () => SiteRoute,
} as any)
const SiteLichAmRoute = SiteLichAmRouteImport.update({
  id: '/lich-am',
  path: '/lich-am',
  getParentRoute: () => SiteRoute,
} as any)
const SiteNgayTotRoute = SiteNgayTotRouteImport.update({
  id: '/ngay-tot',
  path: '/ngay-tot',
  getParentRoute: () => SiteRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/gieo-que': typeof SiteGieoQueRoute
  '/la-so': typeof SiteLaSoRoute
  '/lich-am': typeof SiteLichAmRoute
  '/ngay-tot': typeof SiteNgayTotRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/gieo-que': typeof SiteGieoQueRoute
  '/la-so': typeof SiteLaSoRoute
  '/lich-am': typeof SiteLichAmRoute
  '/ngay-tot': typeof SiteNgayTotRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_site': typeof SiteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/_site/gieo-que': typeof SiteGieoQueRoute
  '/_site/la-so': typeof SiteLaSoRoute
  '/_site/lich-am': typeof SiteLichAmRoute
  '/_site/ngay-tot': typeof SiteNgayTotRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/gieo-que'
    | '/la-so'
    | '/lich-am'
    | '/ngay-tot'
    | '/dashboard/settings'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/gieo-que'
    | '/la-so'
    | '/lich-am'
    | '/ngay-tot'
    | '/dashboard/settings'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_site'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/_site/gieo-que'
    | '/_site/la-so'
    | '/_site/lich-am'
    | '/_site/ngay-tot'
    | '/dashboard/settings'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SiteRoute: typeof SiteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/gieo-que': {
      id: '/_site/gieo-que'
      path: '/gieo-que'
      fullPath: '/gieo-que'
      preLoaderRoute: typeof SiteGieoQueRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/la-so': {
      id: '/_site/la-so'
      path: '/la-so'
      fullPath: '/la-so'
      preLoaderRoute: typeof SiteLaSoRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/lich-am': {
      id: '/_site/lich-am'
      path: '/lich-am'
      fullPath: '/lich-am'
      preLoaderRoute: typeof SiteLichAmRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/ngay-tot': {
      id: '/_site/ngay-tot'
      path: '/ngay-tot'
      fullPath: '/ngay-tot'
      preLoaderRoute: typeof SiteNgayTotRouteImport
      parentRoute: typeof SiteRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SiteRouteChildren {
  SiteGieoQueRoute: typeof SiteGieoQueRoute
  SiteLaSoRoute: typeof SiteLaSoRoute
  SiteLichAmRoute: typeof SiteLichAmRoute
  SiteNgayTotRoute: typeof SiteNgayTotRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteGieoQueRoute: SiteGieoQueRoute,
  SiteLaSoRoute: SiteLaSoRoute,
  SiteLichAmRoute: SiteLichAmRoute,
  SiteNgayTotRoute: SiteNgayTotRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SiteRoute: SiteRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
